config/routes.rb
Waldo::Application.routes.draw do
  root 'home#show'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resource :home, controller: :home, only: :show
  resources :users, only: [:index, :show]
  resources :checkins, only: :create
  resources :areas, only: [:index, :show] do
    resources :zones, only: [:index, :show]
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :zones, dependent: :destroy

  def index
  end
end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  belongs_to :user
  belongs_to :zone
end

app/models/floorplan.rb
class Floorplan < ActiveRecord::Base
  has_many :rooms, dependent: :destroy

  def index

  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :checkins, dependent: :destroy
  belongs_to :area

  def occupants
    users = User.all
    users.select { |u| u.current_room == self }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :checkins

  def active?
    checkins.count > 0 && checkins.last.created_at > 1.days.ago
  end

  def current_zone
    (active? && checkins.last.zone.present?) ? checkins.last.zone : nil
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  has_many :checkins, dependent: :destroy
  belongs_to :area

  def occupants
    users = User.all
    users.select { |u| u.current_zone == self }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_login
    redirect_to :home unless current_user
  end

private
  def must_be_logged_in
    return redirect_to home_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def index
    @areas = Area.all
  end

  def show
    @area = Area.find_by_id(params[:id])

    if request.xhr?
      render partial: 'areas/zones', locals: { zones: @area.zones }
    end
  end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  def create
    if request.xhr?
      x = params[:x]
      y = params[:y]
      zone_id = params[:zone_id]

      Checkin.create!(x: x, y: y, zone_id: zone_id, user: current_user)
    end

    render nothing: true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @areas = Area.all
    @users = User.all.select(&:active?)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :must_be_logged_in

  def index
    @users = User.order('name ASC')
  end

  def show
    @user = User.find_by_id(params[:id])
    @checkins = @user.checkins.order('created_at DESC')
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_filter :must_be_logged_in

  def index
    @area = Area.find_by_id(params[:area_id])
  end

  def show
    @zone = Zone.find_by_id(params[:id])
    @checkins = @zone.checkins.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_photo(user)
    image_tag "http://graph.facebook.com/#{user.uid}/picture?type=small",
              class: 'photo'
  end

  def short_user_name(user)
    words = user.name.split(' ')
    result = words.first
    if words.length > 1
      result += " #{words[1].capitalize.first}."
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
  def area_styles(area)
    "padding-bottom: #{100 / area.aspect_ratio}%;"
  end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_styles(user)
    last_checkin = user.checkins.last
    return '' unless last_checkin.present?
    styles = ''
    styles += "left: #{(last_checkin.x * 100).to_i}%;"
    styles += "top: #{(last_checkin.y * 100).to_i}%;"
    styles
  end
end

app/helpers/zones_helper.rb
module ZonesHelper
  def zone_styles(zone)
    styles = ''
    styles += "left: #{(zone.x * 100).to_i}%;"
    styles += "top: #{(zone.y * 100).to_i}%;"
    styles += "width: #{(zone.width * 100).to_i}%;"
    styles += "height: #{(zone.height * 100).to_i}%;"
    styles
  end
end

app/views/areas/_map.html.haml
.area-map-container{ style: area_styles(area) }
  .area-map{ data: { area_id: area.id } }
    = render 'zones', zones: area.zones

app/views/areas/_zones.html.haml
- zones.each do |zone|
  .area-map-zone{ data: { zone_id: zone.id }, style: zone_styles(zone) }
    .area-map-zone-info
      = zone.name
    - zone.occupants.each do |user|
      .area-map-user{ class: ('me' if user == current_user), style: user_styles(user) }
        = user_photo(user)
        .area-map-user-name
          = short_user_name(user)
        .area-map-user-checkin-time
          = time_ago_in_words(user.checkins.last.created_at)
          ago
.loading-overlay

app/views/areas/index.html.haml
= render 'shared/breadcrumbs',
         breadcrumbs: { 'Areas' => nil }
.areas
  - @areas.each do |area|
    %section.area-section
      %header= link_to area.name, area_path(area)
      = render 'areas/map', area: area

app/views/areas/show.html.haml
= render 'shared/breadcrumbs',
         breadcrumbs: { 'Areas' => areas_path, @area.name => nil }
= link_to pluralize(@area.zones.count, 'Zone'), area_zones_path(@area)
= render 'shared/zone_list', area: @area

app/views/home/show.html.haml
%h3
  Welcome to Waldo!
%p.panel
  Get started by checking in to a zone in the
  = link_to 'areas', areas_path
  section.

app/views/layouts/application.html.haml
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
%head
  %meta{charset: 'utf-8'}
  %meta{name: 'viewpost', content: 'width=device-width, initial-scale=1.0'}

  %title= content_for?(:title) ? yield(:title) : 'Waldo'

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tags

%body{ class: ('logged-out' unless current_user),
       data: { no_turbolink: true } }
  - if current_user
    = render 'shared/nav_bar'
    .main-content
      = yield
    .loader
      Loading...
  - else
    = render 'shared/welcome'
  = javascript_include_tag "application"

app/views/shared/_breadcrumbs.html.haml
%ul.breadcrumbs
  - breadcrumbs.each do |name, url|
    - if url
      %li= link_to name, url
    - else
      %li.current= name

app/views/shared/_nav_bar.html.haml
%nav.top-bar
  %ul.title-area
    %li
      = link_to image_tag('waldo_body.png'), home_path
    %li.toggle-topbar
      = link_to 'Menu', '#'
  %section.top-bar-section
    %ul.left
      %li
        = link_to 'Areas', areas_path
      %li
        = link_to 'Users', users_path
    %ul.right
      %li
        = link_to current_user.name, user_path(current_user)
      %li
        = link_to 'Sign out', signout_path, id: 'sign_out'

app/views/shared/_welcome.html.haml
.welcome
  .welcome-image
    = image_tag 'waldo_causes.png'
  .welcome-login
    = link_to 'Login with Facebook',
              '/auth/facebook',
              id: 'sign_in',
              class: 'button'

app/views/shared/_zone_list.html.haml
%table.zone-list
  %thead
    %tr
      %td Name
      %td # Checkins
      %td Current occupants
      %td Last checkin time
  %tbody
    - area.zones.each do |zone|
      %tr
        %td= link_to zone.name, area_zone_path(area, zone)
        %td= zone.checkins.count
        %td
          - if zone.occupants.length == 0
            None
          - else
            %ul
              - zone.occupants.each do |user|
                %li= user.name
        %td= zone.checkins.count > 0 ? time_ago_in_words(zone.checkins.last.created_at) + ' ago' : 'Never'

app/views/users/index.html.haml
= render 'shared/breadcrumbs',
         breadcrumbs: { 'Users' => nil }
%table
  %thead
    %tr.caption
      %td
      %td Name
      %td # Checkins
      %td Current zone
      %td Last checkin
  %tbody
    - @users.each do |user|
      %tr
        %td.user-photo= user_photo(user)
        %td= link_to user.name, user_path(user)
        %td= user.checkins.count
        %td
          - zone = user.current_zone
          - if zone
            = link_to zone.name, area_zone_path(zone.area, zone)
          - else
            None
        %td= user.checkins.count > 0 ? time_ago_in_words(user.checkins.last.created_at) + ' ago ' : 'Never'

app/views/users/show.html.haml
= render 'shared/breadcrumbs',
         breadcrumbs: { 'Users' => users_path,
                        @user.name => nil }
.user
  .user-info
    .user-photo
      = user_photo(@user)
    .user-name
      = @user.name

  .user-stats
    - zone = @user.current_zone
    - if zone
      .user-stat
        Currently at
        = link_to zone.name.downcase, area_zone_path(zone.area, zone)
  .user-checkins
    - if @checkins.count > 0
      = pluralize(@checkins.count, 'Checkin') + ':'
      %table.user-checkins-list
        %thead
          %tr.caption
            %td= Area
            %td= Zone
            %td= Time
        %tbody
          - @checkins.each do |checkin|
            %tr
              %td= link_to checkin.zone.area.name, area_path(checkin.zone.area)
              %td= link_to checkin.zone.name, area_zone_path(checkin.zone.area, checkin.zone)
              %td= time_ago_in_words(checkin.created_at) + ' ago'
    - else
      No checkins

app/views/zones/index.html.haml
= render 'shared/breadcrumbs',
         breadcrumbs: { 'Areas' => areas_path,
                         @area.name => area_path(@area),
                         'Zones' => nil  }

= render 'shared/zone_list', area: @area

app/views/zones/show.html.haml
= render 'shared/breadcrumbs',
         breadcrumbs: { 'Areas' => areas_path,
                        @zone.area.name => area_path(@zone.area),
                        'Zones' => area_zones_path(@zone.area),
                        @zone.name => nil }

- if @checkins.count > 0
  = pluralize(@checkins.count, 'Checkin') + ':'
  %table.zone-checkins-list
    %thead
      %tr.caption
        %td= User
        %td= Time
    %tbody
      - @checkins.each do |checkin|
        %tr
          %td= link_to checkin.user.name, user_path(checkin.user)
          %td= time_ago_in_words(checkin.created_at) + ' ago'
- else
  No checkins